#Find The Difference:

"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Strategy:
1. first intuition has failed because it didn't take into consideration that the added letter isn't in particularly sorted in an alphabatical order.
2. second answer:
	- save s in a list. Iterate through s and if it's included in t we remove, else it's the added letter so we return it.
	- we also check if the s parameter has characters or not.
3. ellevated answer:
	- use ord() function to get the sum of the characters in each parameter.
	- the difference between the two sums is the code of the added letter. 
"""
# first intuition: failed
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s="".join(sorted(s))
        t="".join(sorted(t))
        if len(t)>len(s):
           return t[-1]
        else:
            return s[-1] 



# accepted
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s=[n for n in s]
        if s:
            for m in t:
                if m in s:
                    s.remove(m)
                else :
                    return m
        else:
            return t


# elevated



    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s1=0
        t1=0
        for n in s:
            s1+=ord(n) #unicode code of a char
        for m in t:
            t1+=ord(m)
        add=t1-s1
        return chr(add) #gives back the chr from the unicode code



